version: '3.7'
services:
  app:
    build:
      args:
        user: node
        uid: 1000
        gid: 1000
      context: .
      dockerfile: Node.dockerfile
      target: 'dev-stage'
    ports:
      - '3500:3000'
    container_name: vue3test
    restart: always
    command: /bin/sh -c "chown -R 1000:1000 /app && cd /app && yarn install && yarn add vue-router@4 && yarn run dev"
    volumes:
      - './app:/app'
    networks:
      - vue3test

networks:
  vue3test:
      name: vue3test_network